thumbor/requirements.txt

To enable this image to be used with Google Cloud Storage, add the
[thumbor-cloud-storage](https://github.com/Superbalist/thumbor-cloud-storage) plugin.

Add Thumbor Cloud Storage

---

thumbor/docker-entrypoint.sh

If the user has already provided a configuration file, we won't generate one from the provided environment variables.
Ref #4

Only generate configuration if none exists

---

thumbor/requirements.txt

Pinning the last python2-compatible version.

Install `cairosvg` for SVG support

---

thumbor/conf/thumbor-circus.ini.tpl

Before, the loglevel was only applied in the `docker-entrypoint.sh` script when running Thumbor solo.

Set Thumbor log level also when running in multiprocess mode with Circus

---

recipes/kubernetes/gce-simple-ingress.yaml

I just got this image running in GCE, so I want to share the simple working configuration before it gets too complicated :)
The key problem I had with GCE is getting the healthcheck probes to work properly.  In the end, the only reliable thing was to modify thumbor to return a 200 on /
The posted yaml uses a docker image that I patched with:
[RUN sed -i "s#/healthcheck#/#g"](https://github.com/MinimalCompact/thumbor/compare/master...ryantxu:ok-on-root#diff-1a159b774759025dee724d110282b167)
Future versions of Thumbor should be able to put the healthcheck on '/':
https://github.com/thumbor/thumbor/pull/1154
```
env:
- name: HEALTHCHECK_ROUTE # See: https://github.com/thumbor/thumbor/pull/1154
value: "/"
```

Add GCE example configuration

---

nginx-proxy/Dockerfile
nginx-proxy/imgpath.js
nginx-proxy/nginx.conf
nginx-proxy/nginx.tmpl

Thumbor [release 6.6.1](https://github.com/thumbor/thumbor/releases/tag/6.6.1) changed the way images are stored on the disc and made Nginx file serving path used in thumbor-nginx-proxy obsolete.
I've made changes to the nginx-proxy so it uses the same hashing mechanism as thumbor.result_storages.file_storage. I've had to use Nginx NJS [Crypto module](https://nginx.org/en/docs/njs/reference.html#crypto) to calculate the file's path.
Now it works as intended as if the file exists on the disk, Nginx serves it directly without making calls to thumbor upstream.

Nginx file serving compatible with thumbor 6.6.1+

---

nginx-proxy/imgpath.js
nginx-proxy/nginx.tmpl

In previous pull request, we've decided to use `.replace()` to fix the issue when Nginx joins two slashes in url into one. Apparently this could be fixed using standard configuration option http://nginx.org/en/docs/http/ngx_http_core_module.html#merge_slashes

Added merge_slashes off to the Nginx config instead of regex in njs

---

recipes/docker-compose/swarm/docker-compose.yml

According to https://github.com/MinimalCompact/thumbor/blob/master/remotecv/docker-entrypoint.sh, we should use REMOTECV_LOADER to specify our loader,  instead of LOADER.

change remotecv config

---

benchmarks/locust/Dockerfile
benchmarks/locust/docker-compose.yml
benchmarks/locust/run_benchmark
benchmarks/locust/scripts/benchmark.py

* created a simple [locust](https://locust.io/) benchmark script to cover
2 types of image manipulation (can be extended to much more)
* running benchmarks with up to 200 concurrent users using 3 locust
slaves and one master
* running benchmark to compare running with:
- Docker processes 1-9 (each docker process has 1 thumbor process)
- Thumbor processes inside docker (one docker process with 1-9 thumbor
processes)
- Built-in threads (1-6) for 1-9 docker processes
* was running benchmarks on a 6 virtual core server

[#14] adding a simple benchmark using locust.io

---

thumbor/Dockerfile
thumbor/requirements.txt

Fixes #36 
I think that would do it.
I am not sure we need to install all these extra packages like `graphicsmagick`, but that is another story.

Fix build installing opencv from pip. Fix pillow-simd builds too

---

thumbor/conf/thumbor.conf.tpl

Fixes #41 
This exposes the AUTO_PNG_TO_JPG as environment variable.
See https://thumbor.readthedocs.io/en/latest/configuration.html#auto-png-to-jpg for further information about this configuration option.
To test this:
Request a transparent PNG image and define a solid background color via filter. Without the option the image would stay a PNG, now it is converted to a JPEG. Same goes for PNG images that do not include an alpha channel at all.
Since usually AUTO_WEBP is enabled, this of course only affects browsers without WebP support like Safari.

Add support for AUTO_PNG_TO_JPG env variable

---

.semaphore/semaphore.yml
tests/nginx-proxy.bats

* see https://github.com/bats-core/bats-core
* only a few basic tests for caching/content-type headers
* one test fails, see #45

adding some simple tests using bats-core

---

thumbor/conf/thumbor.conf.tpl

Ran into a situation where I needed to forward certain headers to the backend, figured I'd add both of these settings.

add more http loader forward settings to thumbor.conf.tpl

---

thumbor/conf/thumbor.conf.tpl
thumbor/requirements.txt

* Update `tc_core` to 0.4.1.
See https://github.com/thumbor-community/core/releases/tag/0.4.1 – this fixes a change in more recent versions of Tornado (see [here](https://github.com/thumbor-community/core/pull/17)).
* Allow to pass `COMMUNITY_EXTENSIONS` to the config file
This is how to activate "community" extensions, see https://github.com/thumbor-community/core#quick-setup.

Bump tc_core to 0.4.1, allow to configure community extensions

---

thumbor/requirements.txt

When trying to use the Sentry env variable thumbor couldn't load the Sentry SDK, by installing the SDK in from the requirements file this will enable the usage of Sentry in from the Docker image directly.
This is also fixing the fallowing issue https://github.com/MinimalCompact/thumbor/issues/75

Include Sentry SDK in requirements file

---

thumbor/Dockerfile

To me, it seems `python:2` is in fact resolved to `python:2.7.18-buster`.

Be more explicit about which Python base image is being used

---

thumbor/requirements.txt

Version is updated to fix `AttributeError: module 'jinja2' has no attribute 'contextfunction'` (described [here](https://github.com/MinimalCompact/thumbor/pull/103#issuecomment-1168511614)).

envtpl version to 0.7.2

---

.github/workflows/build.yaml

Im guessing it wasn't working, so you switched to a PAT. I ran into this once on a personal project, and just had to update the settings to include this repository:
https://github.com/orgs/MinimalCompact/packages/container/thumbor/settings

docker login

---

thumbor/Dockerfile
thumbor/requirements.txt

Upgrade to latest thumbor (at the moment).
Also, suggesting Python 3.11 as base image as it's supported by 7.5.0 version and it has a faster garbage collector.

Upgrade to Thumbor 7.5.0 and Python 3.11

---

thumbor/requirements.txt

Closes #140 
- https://github.com/thumbor/thumbor/releases/tag/7.6.0
- https://github.com/thumbor/thumbor/pull/1592

Upgrade to Thumbor 7.6.0

---

thumbor/requirements.txt

As reported [here](https://github.com/thumbor/thumbor/issues/1622#issuecomment-1814788431), there is a need to pin `opencv-python-headless` version to [4.8.1.78](https://github.com/opencv/opencv-python/releases/tag/78)

chore: added opencv-python-headless to requirements.txt
